### PR TITLE
Xcode classic

### PR DESCRIPTION
**Pull request by mxswd**
Enjoy 2 more build configurations!

### CODE REVIEW

**Comment by mxswd** [comment]
Maybe you can get access to a Big Sur builder for GitHub actions.

**Comment by torarnv** [comment]
Is `swift(>=5.5)` how you do SDK version checks in Swift? Or am I misunderstanding and the constructs used inside those ifdefs are actually relying on Swift 5.5 language features?

**Comment by mxswd** [comment]
I'm not sure it's the best way.

I've been informed you should be checking for a framework that only exists in the new SDK and then you can use it inside switch statements. For example:

```
#if canImport(GroupActivities)
default:
  return false
#endif
```

**Comment by torarnv** [comment]
The framework exists in the macOS 11 SDK as well though.

It doesn't look like Swift has a `__MAC_OS_X_VERSION_MAX_ALLOWED` equivalent so I guess a Swift version check is the closest you get 😞 And doesn't look like you can use `#define` either to have custom `#if HAS_MACOS_12_SDK`. Oh well 😄

**Comment by jspahrsummers** [comment]
Thanks for submitting this, @mxswd! Sorry it's taken me some time to review it.

What's the reason to support Xcode 12? It feels like something that makes life more complicated for little concrete benefit.

Instead, I'd propose we could set the deployment target to Big Sur (while still using the Xcode beta), and use [availability checks](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/marking_api_availability_in_objective-c) to gracefully downgrade functionality. What do you think?

**Review by jspahrsummers — CHANGES_REQUESTED** [review]
Back to you for discussion

**Comment by mxswd** [comment]
The only benefit is you can do Xcode builds for at least the next month (it will built with GH actions). I think targeting macOS 11 is worth it while Xcode 12 is not. I will change things up and come back later.

- [ ] remove Xcode 12 ifdefs
- [ ] fix SwiftUI around disk management on macOS 11

**Comment by mxswd** [comment]
This can only run linux VMs so there is no point adding availability checks or backwards deploying at all.

**Comment by jspahrsummers** [comment]
sorry

**Pull request closed without merging**
